/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_58D415CC__
#define __PLUGINEDITOR_H_58D415CC__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class TripleTremoloAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    TripleTremoloAudioProcessorEditor (TripleTremoloAudioProcessor* ownerFilter);
    ~TripleTremoloAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_58D415CC__
